from typing import Any

CATALOG: list[dict[str, Any]] = [
    {
        "id": "fixture-image",
        "display_name": "Fixture Image",
        "provider": "creativo",
        "modality": "image",
        "enabled": True,
        "status": "active",
        "summary": "Platform proof model. Renders a labeled fixture so the loop can be tested without a GPU.",
        "version": "v1",
        "container_image": "creativo/fixture-image:v1",
        "weights_version": "none",
        "required_vram_gb": 0,
        "supported_gpus": ["cpu"],
        "credit_cost": 1,
        "pricing_status": "measured",
        "timeout_seconds": 20,
        "max_attempts": 2,
        "capabilities": {
            "text_to_image": True,
            "image_to_image": True,
            "text_to_video": False,
            "image_to_video": False,
            "multi_image_to_video": False,
            "audio": False,
            "max_reference_images": 1,
            "aspect_ratios": ["1:1", "3:2", "2:3", "16:9", "9:16"],
            "resolutions": ["512", "1024"],
            "supports_batching": True,
            "max_batch_size": 5,
            "supports_concurrency": False,
            "max_concurrent_jobs": 1,
        },
    },
    {
        "id": "qwen-image",
        "display_name": "Qwen Image",
        "provider": "qwen",
        "modality": "image",
        "enabled": True,
        "status": "active",
        "summary": "Qwen-Image-2512, Apache-2.0. Loads for one picture, then leaves the GPU.",
        "version": "v1",
        "container_image": "creativo/qwen-image:v1",
        "weights_version": "Qwen/Qwen-Image-2512",
        "required_vram_gb": 48,
        "supported_gpus": ["A100"],
        "credit_cost": 4,
        "pricing_status": "estimate",
        "timeout_seconds": 900,
        "max_attempts": 2,
        "capabilities": {
            "text_to_image": True,
            "image_to_image": False,
            "text_to_video": False,
            "image_to_video": False,
            "multi_image_to_video": False,
            "audio": False,
            "max_reference_images": 0,
            "aspect_ratios": ["1:1", "3:2", "2:3", "16:9", "9:16"],
            "resolutions": ["1024"],
            "supports_batching": False,
            "max_batch_size": 1,
            "supports_concurrency": False,
            "max_concurrent_jobs": 1,
        },
    },
    {
        "id": "flux",
        "display_name": "Flux",
        "provider": "black-forest-labs",
        "modality": "image",
        "enabled": True,
        "status": "active",
        "summary": "FLUX.1 schnell, Apache-2.0. Separate requests for this model share one GPU pass, up to five different prompts.",
        "version": "v1",
        "container_image": "creativo/flux-schnell:v1",
        "weights_version": "black-forest-labs/FLUX.1-schnell+city96/FLUX.1-schnell-gguf/flux1-schnell-Q4_K_S.gguf",
        "required_vram_gb": 6,
        "supported_gpus": ["3050", "4090", "L40S", "A100"],
        "credit_cost": 2,
        "pricing_status": "estimate",
        "timeout_seconds": 900,
        "max_attempts": 2,
        "capabilities": {
            "text_to_image": True,
            "image_to_image": True,
            "text_to_video": False,
            "image_to_video": False,
            "multi_image_to_video": False,
            "audio": False,
            "max_reference_images": 1,
            "aspect_ratios": ["1:1", "3:2", "2:3", "16:9", "9:16"],
            "resolutions": ["512", "1024"],
            "supports_batching": True,
            "max_batch_size": 5,
            "supports_concurrency": False,
            "max_concurrent_jobs": 1,
        },
    },
    {
        "id": "wan",
        "display_name": "Wan",
        "provider": "alibaba",
        "modality": "video",
        "enabled": False,
        "status": "planned",
        "summary": "First video candidate. A warm high-VRAM pool is a cost decision, not the default.",
        "version": "v1",
        "container_image": "ai-wan:v1",
        "weights_version": "unpinned",
        "required_vram_gb": 80,
        "supported_gpus": ["H100", "H200", "A100"],
        "credit_cost": 15,
        "pricing_status": "estimate",
        "timeout_seconds": 600,
        "max_attempts": 2,
        "capabilities": {
            "text_to_image": False,
            "image_to_image": False,
            "text_to_video": True,
            "image_to_video": True,
            "multi_image_to_video": False,
            "audio": False,
            "max_reference_images": 1,
            "aspect_ratios": ["16:9", "9:16", "1:1"],
            "resolutions": ["720p"],
            "durations": [5],
            "supports_batching": False,
            "max_batch_size": 1,
            "supports_concurrency": False,
            "max_concurrent_jobs": 1,
        },
    },
    {
        "id": "minimax-h3",
        "display_name": "MiniMax H3",
        "provider": "minimax",
        "modality": "video",
        "enabled": False,
        "status": "planned",
        "summary": "Multi-reference video candidate. Enable only if the weights can run inside a worker, not as a closed API.",
        "version": "v1",
        "container_image": "ai-minimax-h3:v1",
        "weights_version": "unpinned",
        "required_vram_gb": 141,
        "supported_gpus": ["H200"],
        "credit_cost": 25,
        "pricing_status": "estimate",
        "timeout_seconds": 900,
        "max_attempts": 2,
        "capabilities": {
            "text_to_image": False,
            "image_to_image": False,
            "text_to_video": True,
            "image_to_video": True,
            "multi_image_to_video": True,
            "audio": True,
            "max_reference_images": 9,
            "aspect_ratios": ["16:9", "9:16"],
            "resolutions": ["720p", "1080p"],
            "durations": [6, 8],
            "supports_batching": False,
            "max_batch_size": 1,
            "supports_concurrency": False,
            "max_concurrent_jobs": 1,
        },
    },
]
